---
- name: Aplicar patches em sistemas Red Hat
  hosts: all
  become: yes
  tasks:
    - name: Atualizar repositórios
      yum:
        name: '*'
        state: latest

    - name: Verificar se é necessário reiniciar
      command: needs-restarting -r
      ignore_errors: yes
      register: restart_check

    - name: Reiniciar se necessário
      command: reboot
      async: 1
      poll: 0
      ignore_errors: yes
      when: restart_check.rc == 0
    - name: Enviar e-mail com resultado
      mail:
        host: "smtp.gmail.com"
        port: "465"
        from: "paulocesar20499@gmail.com"
        to: "plcersar@gmail.com"
        subject: "Resultado da tarefa"
        body: "O resultado da tarefa foi: {{ resultado_tarefa.stdout }}"
       when: resultado_tarefa.rc == 0 
