---
- name: Aplicar patches em sistemas Debian
  hosts: all
  become: yes
  tasks:
    - name: Atualizar repositórios
      apt:
        update_cache: yes

    - name: Atualizar pacotes
      apt:
        upgrade: dist
        update_cache: yes
      register: upgrade_result

    - name: Verificar se é necessário reiniciar
      command: needs-restarting -r
      ignore_errors: yes
      register: restart_check

    - name: Reiniciar se necessário
      command: reboot
      async: 1
      poll: 0
      ignore_errors: yes
      when: restart_check.rc == 0


