---
- name: Atualizar sistema Linux
  hosts: linux_servers
  become: yes
  tasks:
    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
      become_method: sudo
      tags:
        - linux_updates

    - name: Atualizar lista de pacotes
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
      become_method: sudo
      tags:
        - linux_updates
