- hosts: all
- name: Install Apache Web Server
  hosts: all
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install apache2
      apt:
        name: apache2
        state: present
    - name: Ensure myfile.txt has 755 permissions
      file:
        path: /var/www/html/
        mode: '0777'
        
  tasks:
    - name: Atualizar informações sobre pacotes
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'  # Para sistemas Debian/Ubuntu

    - name: Instalar pacotes
      package:
        name: 
          - vim
          - htop
          - zip
          - samba
          - apache2
        state: present  # Para garantir que os pacotes estejam instalados
