- hosts: all
- name: Install Apache Web Server
  hosts: all
 # become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install apache2
      apt:
        name: apache2
        state: present
    - name: Ensure myfile.txt has 755 permissions
      file:
        path: /var/www/html/
        mode: '0777'
