- name: Instalação do PHP
  hosts: all
  become: yes
  tasks:
    - name: Instalar PHP (Ubuntu/Debian)
      apt:
        name: php
        state: present
      when: ansible_os_family == "Debian"
      tags:
        - php

    - name: Instalar PHP (CentOS/RHEL)
      yum:
        name: php
        state: present
      when: ansible_os_family == "RedHat"
      tags:
        - php
