---
- hosts: all
  tasks:
     - name: "instalando pacotes para wordpress"
       apt:
         name: "{{ item }}"
         state: latest
       become: yes
       with_items:
         - php8.2
         - apache2
         - libapache2-mod-php8.2
         - php8.2-mysql
         - python-mysqldb
         - php8.2-gd
         - libssh2-php
         - php8.2-mcrypt
         
